### PR TITLE
WIP: Virtual font kern

### LINKED ISSUE #242: Generate KERN table for the Preview (VirtualFont)
A vital step toward having a kerning and metrics editor, is having the ability to display kerning in the preview.

### PR DESCRIPTION
**Pull request by xorgy**
Compute a `kern` table for the Preview.

Intended to resolve #242

### CODE REVIEW

**Comment by xorgy** [comment]
I think I got something subtly wrong in this since it doesn't seem to show up, but at least it doesn't crash.

**Comment by xorgy** [comment]
For whatever reason I forgot that `kern` is unused with OpenType, oof.

**Comment by xorgy** [comment]
I'm going to look at implementing a subset of `GPOS` that can handle the basic kerning use case.

**Comment by madig** [comment]
`kern` is used and HarfBuzz can use it, but outside of legacy applications like an up to date Powerpoint, it has been superseded by `GPOS`.

**Pull request closed without merging**
