### PR TITLE
Add toolbar widget with actual icons

### PR DESCRIPTION
**Pull request by cmyr**
This is based on some of eli's sketches in #43.

The icons are *perhaps* a little rough, but my intention is that when the editor picks up features (ideally rapidly, over the next while) we can use it to redraw them, and we can keep them in a UFO file in source control. 

Screen Shot 2020-05-14 at 5 55 15 PM

### CODE REVIEW

**Comment by madig** [comment]
Love the hand, let's keep it forever.

**Comment by eliheuer** [comment]
I like the idea of using UFO for the icons, maybe using the [private use area](https://en.wikipedia.org/wiki/Private_Use_Areas) code points?

If the icons are all in one UFO file, it would be easy for someone to make a custom icon set and share it on GitHub, then changing the icon set might be as simple as swapping the custom UFO with the standard icon set UFO in the source and rebuilding.

**Comment by cmyr** [comment]
Yea, something like that could be possible? If we want the icons to actually have some styling (not just be outlines but have some paths filled, and maybe be two tone) that might get a bit trickier, since we might do some processing on the individual icons?

Also not sure i'm too worried about assigning them meaningful codepoints, although we certainly could? We could also just expect certain names or what-have-you.

**Comment by madig** [comment]
Once Runbender can handle https://www.colorfonts.wtf/, anything is possible.

**Pull request merged**
