### PR TITLE
Add redesigned toolbar widget icons

### PR DESCRIPTION
**Pull request by eliheuer**
I did a full redesign of the toolbar widget icons. I tried to create better visual continuity between each icon and made some adjustments to help clarify each tool's use case. Please see the screenshot below.

The UFO source file for the icons used for this PR is here: https://github.com/eliheuer/runebender-icons/tree/main/ufo-icon-source/toolsbar-icons.ufo at commit `8af9f24`.

rb-toolsbar-widget-update

And for reference, the screenshot below is the toolbar widget icons before the redesign.

pre-rb-toolsbar-widget-update

### CODE REVIEW

**Comment by alerque** [comment]
Yes!

I skimmed this message too fast the first time and thought (assumed) the second image was the "after" state. I quickly decided this was a regression and wondered what you were thinking. Then it hit me which set was familiar from my minor tinkering use. Oops!

That's how much better these are, my brain accepted the new ones instantly without even thinking about it and immediately saw the old ones as worse.

**Review by alerque — APPROVED** [review]

**Review by cmyr — APPROVED** [review]
Looks great, thanks eli!

**Comment by ctrlcctrlv** [comment]
I thought this comment would appear here, but it didn't:

https://github.com/linebender/runebender/commit/56e964135b99fd69dcfb24857bf643cd123a3f3a#commitcomment-50500568

**Comment by eliheuer** [comment]
@ctrlcctrlv At some point, I would like to try making bitmap icons in Blender and getting those working in a fork or custom theme of Runebender, and it would be nice if creating custom icons was easier.

But the way this works is fine with me for now, I copy drawings from Runebender and paste them into this file.

**Comment by alerque** [comment]
If that's how this works, that workflow should be wired up somehow. Perhaps the app source should just have `.glif` files for the icons and load/convert them to it's internal canvas drawing commands automatically. A side-loaded drawing and copy/paste routine doesn't "share" well, as @ctrlctrlv points out.

**Comment by eliheuer** [comment]
@alerque Yeah that would be nice, I really want customization and theming to be a relatively easy entry point into customizing the editor, maybe a UFO file for the icons could go in `runebender/resources` with the theme files?

**Comment by eliheuer** [comment]
I made an issue to move the icons to a UFO in `resources`. https://github.com/linebender/runebender/issues/248

**Pull request merged**
