### PR TITLE
Fresh start

### PR DESCRIPTION
**Pull request by cmyr**
This is a dump of state of the new runebender application. Current status: you can open a UFO file and scroll through the glyphs. Some of them even render!

I'll merge this when I start working tomorrow, this PR is more of a heads-up. :)

Screen Shot 2019-09-30 at 5 15 17 PM

### CODE REVIEW

**Comment by madig** [comment]
Idle thought: does the logic handle nested components and unavailable components? It would be nice if the app could later replace unavailable components with placeholders to make them visible and give the user the chance to change them to something else.

**Comment by cmyr** [comment]
This doesn't handle components currently, although I'd like to get that working very shortly.

How significant a problem are unavailable components? My thinking would be that if a component is in a glyph it should be in the file, and if it isn't that would be a fairly serious issue with the data. Is this a more common problem then I realize?

**Comment by madig** [comment]
I can happen in the heat of font design (if you copy glyphs around from one file to another, ...), when scripts go wrong, etc. It should be handled gracefully. Glyphs displays a placeholder so the user knows what's up and can click on it to change it to a different component, or insert the missing glyph.

**Comment by madig** [comment]
Oh, and: IIRC, the UFO spec says that components always reference glyphs in the same layer (because layers contain glyphs). This is different from the Glyphs file format (where glyphs contain layers), where I have found designers in the wild doing this: https://github.com/googlefonts/glyphsLib/issues/375. This should probably be a test case.

**Comment by cmyr** [comment]
I was confused by that point, actually; in UFO is a glyph contained in a single layer? I assumed that a glyph, when displayed, was combining each layer that contained a glyph with the same name, and that this would also be true for components; when resolving a component you would include all of its layers?

**Comment by madig** [comment]
AFAIK, each layer can independently hold any glyph, so you could have a default layer with "a", "b" and "c" and a layer "sdkjdfkdsj" with "u" and "x". Components always refer to glyphs of the same layer. There is no combination going on that I am aware of. Layers are like different planes of existance.

**Pull request merged**
